### ISSUE TITLE
TypeError: StyleScope.removeTaggedAdditionalCSS is not a function

### ISSUE THREAD

**Issue by vikasacharya16** [NathanaelA/nativescript-themes#9]
on apps.js i wrote this thats all

```
var themes = require('nativescript-themes');
themes.applyTheme('custom.css');
```

nativescript version

```
"nativescript": {
        "id": "org.ns.theme_changer",
        "tns-ios": {
            "version": "4.2.0"
        },
        "tns-android": {
            "version": "5.2.1"
        }
    },
```
i got this error

```
System.err: com.tns.NativeScriptException:
System.err: Calling js method run failed
System.err: TypeError: StyleScope.removeTaggedAdditionalCSS is not a function
System.err: File: "file:///data/data/org.megahard.tech_display/files/app/tns_modules/nativescript-themes/themes.js, line: 115, column: 26
System.err: StackTrace:
System.err:     Frame: function:'internalLoadCss', file:'file:///data/data/org.megahard.tech_display/files/app/tns_modules/nativescript-themes/themes.js', line: 115, column: 27
System.err:     Frame: function:'', file:'file:///data/data/org.megahard.tech_display/files/app/tns_modules/nativescript-themes/themes.js', line: 109, column: 4
System.err:     Frame: function:'invoke', file:'file:///data/data/org.megahard.tech_display/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 19, column: 48
System.err:     Frame: function:'run', file:'file:///data/data/org.megahard.tech_display/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 23, column: 13
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1203)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1083)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1070)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1050)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1042)
System.err:     at com.tns.gen.java.lang.Runnable.run(Runnable.java:15)
System.err:     at android.os.Handler.handleCallback(Handler.java:742)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
System.err:     at android.os.Looper.loop(Looper.java:157)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:5601)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:774)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)
```

same thing i did a sample on playground which is working fine
https://play.nativescript.org/?template=play-js&id=sjmFcQ

**Comment by NathanaelA** [comment]
In your `package.json`; which version of `tns-core-modules`?  My guess is you are using an older version that doesn't support this code...     You need to be running core modules of at least 5.x ..

**Comment by NathanaelA** [comment]
Please note I just retested this under NS 5.4 and everything is working correctly.
